// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "true-life-purpose-coaching-bucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://true-life-purpose-coaching-bucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:9e092050-42e2-4422-96ef-412838168a37",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3EQI7R4Fc",
    "aws_user_pools_web_client_id": "4d8p0shodk50qimd6vu7ag4173",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ah6zee5dmfanxalhkccych6kgu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4dzvocdktnezrhxu3ryf4okmlm"
}
export default awsmobile